### ISSUE TITLE
Challenge program error message

### ISSUE THREAD

**Issue by you06** [you06/challenge-program#1]
Currently, some error message will bring confuse to challenge program players, we need to make it better and give some helpful message.

- [ ] [error message: pick up a non-task issue #2](https://github.com/you06/challenge-program/issues/2)
- [ ] [error message: mispick level #3](https://github.com/you06/challenge-program/issues/3)
- [ ] [error message: typo notice #5](https://github.com/you06/challenge-program/issues/5)
